http:
  port: 3000
admin:
  port: 9876
  host: localhost
apiEndpoints:
  helloworld:
    host: localhost
    path: '/hola-mundo'
serviceEndpoints:
  helloWorldServices:
    url: 'http://localhost:3001'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  helloworldPipeline:
    apiEndpoints:
      - helloworld
    policies:
      - proxy:
          - action:
              serviceEndpoint: helloWorldServices
              ignorePath:   false
              prependPath:   true
              stripPath:   true
              changeOrigin: true