http:
  port: 3000
admin:
  port: 9876
  host: localhost
apiEndpoints:
  welcomeMessage:
    host: localhost
    path: '/mensajeBienvenida'
  
  weather:
    host: localhost
    paths: '/clima/:ciudad'

  news:
    host: localhost
    paths: '/noticias/:category'

serviceEndpoints:
  welcomeMessageServices:
    url: 'http://localhost:3001'

  newsService:
    url: 'http://localhost:3002'

  weatherService:
    url: 'http://localhost:3003'

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  welcomeMessagePipeline:
    apiEndpoints:
      - welcomeMessage
    policies:
      - cors:
      - proxy:
          - action:
              serviceEndpoint: welcomeMessageServices
              ignorePath:   false
              prependPath:   true
              stripPath:   true
              changeOrigin: true

  weatherPipeline:
    apiEndpoints:
      - weather
    policies:
      - cors:
      - proxy:
          - action:
              serviceEndpoint: weatherService
              ignorePath:   false
              prependPath:   true
              stripPath:   true
              changeOrigin: true
      - log:
          - action:
              message: "Procesando solicitud de clima"
  
  newsPipeline:
    apiEndpoints:
      - news
    policies:
      - cors:
      - proxy:
          - action:
              serviceEndpoint: newsService
              ignorePath:   false
              prependPath:   true
              stripPath:   true
              changeOrigin: true
      - log:
          - action:
              message: "Procesando solicitud de noticias"