http:
  port: 3000
admin:
  port: 9876
  host: localhost
apiEndpoints:
  helloworld:
    host: localhost
    path: '/hola-mundo'
  
  weather:
    host: localhost
    paths: '/api/clima/:ciudad'

serviceEndpoints:
  helloWorldServices:
    url: 'http://localhost:3001'

  weatherService:
    url: 'http://localhost:2500'

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  helloworldPipeline:
    apiEndpoints:
      - helloworld
    policies:
      - proxy:
          - action:
              serviceEndpoint: helloWorldServices
              ignorePath:   false
              prependPath:   true
              stripPath:   true
              changeOrigin: true

  weatherPipeline:
    apiEndpoints:
      - weather
    policies:
      - cors:
      - proxy:
          - action:
              serviceEndpoint: clima_service
              ignorePath:   false
              prependPath:   true
              stripPath:   true
              changeOrigin: true
      - log:
          - action:
              message: "Procesando solicitud de clima"